title: DoMates
description: Shared chore management for roommates, couples & families.
theme: minima
url: "" # Update to https://<your-username>.github.io
baseurl: "/domates-support"

author:
  name: DoMates Team
  email: your@email.com # Replace with your actual email

plugins:
  - jekyll-seo-tag
